sudo: false
language: go
go:
  - 1.10.x
env:
  - DEP_VERSION=0.5.0
matrix:
  allow_failures:
    - go: master
  fast_finish: true
before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
install:
  - # Do nothing. This is needed to prevent default install action "go get -t -v ./..." from happening here (we want it to happen inside script step).
script:
  - dep ensure
  - go install github.com/camd67/moebot/moebot_bot
  - diff -u <(echo -n) <(gofmt -d -s ./moebot_bot)
  - go tool vet ./moebot_bot
  - go test -v -race ./moebot_bot/...
