[psql]
	dbname 	= 
	host	= 
	port	= 
	user	= 
	pass 	= 
	schema	= 
	sslmode	= 
	

	
[[types]]
	[types.match]
	name = "group_type"
	
	[types.replace]
	type	=	"types.GroupType"
	
	[types.imports]
	third_party = ['"github.com/camd67/moebot/moebot_bot/util/db/types"']
	
[[types]]
	[types.match]
	name = "permission"
	
	[types.replace]
	type	=	"types.Permission"
	
	[types.imports]
	third_party = ['"github.com/camd67/moebot/moebot_bot/util/db/types"']
	
[[types]]
	[types.match]
	name = "raffle_type"
	
	[types.replace]
	type	=	"types.RaffleType"
	
	[types.imports]
	third_party = ['"github.com/camd67/moebot/moebot_bot/util/db/types"']
	
[[types]]
	[types.match]
	name = "scheduler_type"
	
	[types.replace]
	type	=	"types.SchedulerType"
	
	[types.imports]
	third_party = ['"github.com/camd67/moebot/moebot_bot/util/db/types"']