// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Channel            string
	ChannelRotation    string
	GroupMembership    string
	Metric             string
	Poll               string
	PollOption         string
	RaffleEntry        string
	Role               string
	RoleGroup          string
	ScheduledOperation string
	Server             string
	UserProfile        string
	UserServerRank     string
}{
	Channel:            "channel",
	ChannelRotation:    "channel_rotation",
	GroupMembership:    "group_membership",
	Metric:             "metric",
	Poll:               "poll",
	PollOption:         "poll_option",
	RaffleEntry:        "raffle_entry",
	Role:               "role",
	RoleGroup:          "role_group",
	ScheduledOperation: "scheduled_operation",
	Server:             "server",
	UserProfile:        "user_profile",
	UserServerRank:     "user_server_rank",
}
